### ISSUE TITLE
Use Travis-CI for automated build checks

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#5]
We will only need a script that will install all dependencies and builds Kaidan.
The builds run on ubuntu VMs.

Here is an example how the config file could look like:
`.travis.yml`
```yml
language: cpp
before_install: ./util/travis/before_install.sh
script: ./util/travis/script.sh
sudo: required
notifications:
  email: false
matrix:
  fast_finish: true
  include:
    - env: PLATFORM=Win32
      compiler: gcc
      os: linux
    - env: PLATFORM=Win64
      compiler: gcc
      os: linux
    - env: PLATFORM=Unix COMPILER=clang
      compiler: clang
      os: osx
    - env: PLATFORM=Unix COMPILER=g++
      compiler: gcc
      os: linux
    - env: PLATFORM=Unix COMPILER=clang
      compiler: clang
      os: linux
    - env: PLATFORM=Unix COMPILER=g++-6
      compiler: gcc
      os: linux
```

Here is a good example for using it:
https://travis-ci.org/minetest/minetest

You can also add a PNG to the README that show if the latest build has failed:
https://github.com/minetest-games/af8

The only thing we need is a working build script, that installs all dependencies and creates a build (on ubuntu, for all possible platforms).
